### ISSUE TITLE
pod with multiple containers is not being injected

### ISSUE THREAD

**Issue by raffaelespazzoli** [aws/amazon-eks-pod-identity-webhook#109]
**What happened**:

I'm deploying a pod with 3 containers and 1 init container. The init container needs to pull something from s3 and needs the credentials to do so.
None of the containers is being injected with the projected service account and env variables.

**What you expected to happen**:
I expected all the containers to be injected or to be able to some specify which container should be injected.

**How to reproduce it (as minimally and precisely as possible)**:
my environment might be hard to reproduce as I have istio, knative and kfserving. But in attachment I put the spec of the pod that is failing, as you can see it does not have the injected projected account. ans you can probably sue this manifest for the tests.
[pod-spec.txt](https://github.com/aws/amazon-eks-pod-identity-webhook/files/6124283/pod-spec.txt)

The service account looks like this:
```yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    eks.amazonaws.com/audience: sts.amazonaws.com
    eks.amazonaws.com/token-expiration: '86400''
  name: default-editor
  namespace: raffa
secrets:
  - name: default-editor-token-ccqcw
  - name: default-editor-dockercfg-fmnhp
imagePullSecrets:
  - name: default-editor-dockercfg-fmnhp
```

**Anything else we need to know?**:
istio has its own pod mutating web hook, not sure if that matters.

**Environment**:
- AWS Region: us-west-1
- EKS Platform version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.platformVersion`): no EKS. Using OpenShift.
- Kubernetes version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.version`):

```shell
oc version
Client Version: 4.7.0
Server Version: 4.7.0
Kubernetes Version: v1.20.0+bd9e442
```

- Webhook Version:
```shell
/usr/bin/aws-pod-identity-webhook --version
v0.1.0
```
