### ISSUE TITLE
Annotations eks.amazonaws.com/skip-containers and eks.amazonaws.com/sts-regional-endpoints aren't working

### ISSUE THREAD

**Issue by shardulsrivastava** [aws/amazon-eks-pod-identity-webhook#123]
**What happened**:

I am using EKs version 1.21 and trying to use IRSA, for that m setting these annotations :
```yaml
eks.amazonaws.com/sts-regional-endpoints: "true
eks.amazonaws.com/skip-containers: sidecar-busybox-container
```

however, the container is still getting injected with environment variables for container `sidecar-busybox-container`  and I don't see the use of STS regional endpoints with the pod.

**What you expected to happen**:

as per the docs, here it should have skipped  mutating `sidecar-busybox-container` container and add the environment variable `AWS_STS_REGIONAL_ENDPOINTS` to use regional STS endpoints. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a cluster with the below YAML
```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: iam-cluster
  region: us-east-1
  version: "1.21"

availabilityZones: 
  - us-east-1a
  - us-east-1b
  - us-east-1c

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: s3-reader
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"

managedNodeGroups:
  - name: managed-ng-1
    instanceType: t3a.medium
    minSize: 1
    maxSize: 4
    desiredCapacity: 
```

2. Annotate the service account `s3-reader` with these annotations : 
```bash
kubectl annotate \
  sa s3-reader \
    "eks.amazonaws.com/audience=sts.amazonaws.com" \
    "eks.amazonaws.com/sts-regional-endpoints=true" \
    "eks.amazonaws.com/token-expiration=43200" \
    "eks.amazonaws.com/skip-containers=sidecar-busybox-container"
```
3. Create  a pod with 2 containers : 
```bash
apiVersion: v1
kind: Pod
metadata:
  name: iam-test
spec:
  serviceAccountName: s3-reader
  restartPolicy: Never
  containers:
  - name: iam-test
    image: amazon/aws-cli
    args: [ "sts", "get-caller-identity" ]

  - name: sidecar-busybox-container
    image: radial/busyboxplus:curl
```

once the pod is created, check the environment variables for the containers :

```bash
kubectl get pods iam-test -ojson|jq -r '.spec.containers[].env)'
```

 

**Anything else we need to know?**:

**Environment**: EKS v1.21
- AWS Region: us-east-1
- EKS Platform version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.2"
- Kubernetes version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.version`): 1.21
- Webhook Version: Not sure how to get it from the cluster.
