### ISSUE TITLE
Incompatible with grpc health probes

### ISSUE THREAD

**Issue by mikberg** [aws/amazon-eks-pod-identity-webhook#165]
**What happened**:

gRPC probes were introduced in Kubernetes 1.24, adding a new field `grpc` to `Probe` (used in `readinessProbe` and `livenessProbe`). The pod identity webhook seems to be incompatible with this. Pods with a service account with the `eks.amazonaws.com/role-arn` annotation can't be created:

```
The Pod "test-grpc" is invalid: spec.containers[0].readinessProbe: Required value: must specify a handler type
```

**What you expected to happen**:

gRPC probes working, and the pod identity webhook working

**How to reproduce it (as minimally and precisely as possible)**:

Observe that this example pod can be deployed and works as expected:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-grpc
spec:
  containers:
  - name: agnhost
    image: k8s.gcr.io/e2e-test-images/agnhost:2.35
    command: ["/agnhost", "grpc-health-checking"]
    ports:
    - containerPort: 5000
    - containerPort: 8080
    readinessProbe:
      grpc:
        port: 5000
```

Create a Kubernetes service account `my-sa` with the `eks.amazonaws.com/role-arn` annotation set, and try to use it in a new pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-grpc
spec:
  serviceAccountName: my-sa
  containers:
  - name: agnhost
    image: k8s.gcr.io/e2e-test-images/agnhost:2.35
    command: ["/agnhost", "grpc-health-checking"]
    ports:
    - containerPort: 5000
    - containerPort: 8080
    readinessProbe:
      grpc:
        port: 5000
```

This error message is returned:

```
The Pod "test-grpc" is invalid: spec.containers[0].readinessProbe: Required value: must specify a handler type
```

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-north-1
- EKS Platform version: eks.3
- Kubernetes version: 1.24
- Webhook Version: ?
