### ISSUE TITLE
Jsonpatch operation fails if automountServiceAccountToken is false and no volumes are defined

### ISSUE THREAD

**Issue by FaHeymann** [aws/amazon-eks-pod-identity-webhook#17]
**What happened**:

A ServiceAccount with `automountServiceAccountToken: false` and the EKS IAM Annotation failed to spawn a Pod from a Job definition that did not define Volumes on the Pod with the following Error

```
Events:
  Type     Reason        Age                From            Message
  ----     ------        ----               ----            -------
  Warning  FailedCreate  16s (x2 over 26s)  job-controller  Error creating: Internal error occurred: Internal error occurred: jsonpatch add operation does not apply: doc is missing path: "/spec/volumes/0"
```

https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/pkg/handler/handler.go#L158-L177 probably needs to check if `/spec/volumes` already exists. If `automountServiceAccountToken` on the ServiceAccount is true, there is always a volume present on the Pod, if set to false this is no longer the case though.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  name: test
  namespace: test
  annotations:
    eks.amazonaws.com/role-arn: <redacted>
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test
  namespace: test
spec:
  template:
    spec:
      restartPolicy: "Never"
      containers:
      - image: nginx
        name: my-container
      securityContext:
        fsGroup: 1000
      serviceAccountName: test
```

**Anything else we need to know?**:

**Environment**:
- AWS Region: eu-central-1
- EKS Platform version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.1
- Kubernetes version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.version`): 1.14
- Webhook Version:
