### ISSUE TITLE
Injection of region environment variables appears to ignore `envFrom.configMapRef`

### ISSUE THREAD

**Issue by badgerspoke** [aws/amazon-eks-pod-identity-webhook#248]
**What happened**:
- I tried to run a pod in EKS 1.31 (from a Cron) that needs to do cross-region S3 puts, making use of IRSA (with suitable, known working, bucket and IAM policy - this is not an IRSA issue)
- My pod gets environment from a ConfigMap which includes `AWS_REGION` and `AWS_DEFAULT_REGION`
- When the container runs, the values for `AWS_REGION` and `AWS_DEFAULT_REGION` are set not from the ConfigMap values but from the cluster runtime environment region

**What you expected to happen**:
- I expected the values to be those from the ConfigMap

**How to reproduce it (as minimally and precisely as possible)**:
- In a cluster in, say, `eu-central-1` use this simple manifest:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::REDACTED:role/foo

---
apiVersion: v1
kind: ConfigMap
data:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_REGION: ap-southeast-1
metadata:
  name: test-backup-cron-vars
  namespace: default

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-backup-cron
  namespace: default
spec:
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: foo
          containers:
            - args:
                - env|grep AWS
              command:
                - /bin/bash
                - -c
                - --
              envFrom:
                - configMapRef:
                    name: test-backup-cron-vars
              image: ubuntu:latest
              imagePullPolicy: IfNotPresent
              name: backup-cron
  schedule: 45 20 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
  timeZone: Etc/UTC
```
- Apply the manifest, run the job and observe output:
```
% kc  logs test-backup-cron-manual-95vdx-9fq97
AWS_DEFAULT_REGION=eu-central-1
AWS_REGION=eu-central-1
AWS_ROLE_ARN=arn:aws:iam::REDACTED:role/foo
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_STS_REGIONAL_ENDPOINTS=regional
```
- Observe env set on the pod:
```
% kc  describe pod test-backup-cron-manual-95vdx-9fq97
Name:             test-backup-cron-manual-95vdx-9fq97
Namespace:        default
Priority:         0
Service Account:  foo
...
Containers:
  backup-cron:
    Container ID:  containerd://445eb6a0d73c872b642f764d74dc1a0a1860ead0a10f315034f5bcc15d256453
    Image:         ubuntu:latest
    Image ID:      docker.io/library/ubuntu@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -c
      --
    Args:
      env|grep AWS
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 06 Dec 2024 15:52:59 +1100
      Finished:     Fri, 06 Dec 2024 15:52:59 +1100
    Ready:          False
    Restart Count:  0
    Environment Variables from:
      test-backup-cron-vars  ConfigMap  Optional: false
    Environment:
      AWS_STS_REGIONAL_ENDPOINTS:   regional
      AWS_DEFAULT_REGION:           eu-central-1
      AWS_REGION:                   eu-central-1
      AWS_ROLE_ARN:                 arn:aws:iam::REDACTED:role/foo
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-m5kzk (ro)
```

**Anything else we need to know?**: Surely I cannot be the first person to hit this?!

**Environment**:
- AWS Region: `eu-central-1`
- EKS Platform version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.platformVersion`): `eks.12`
- Kubernetes version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.version`): `1.31`
- Webhook Version:
