### ISSUE TITLE
Inject AWS_REGION environment variable into pods

### ISSUE THREAD

**Issue by walkley** [aws/amazon-eks-pod-identity-webhook#40]
**What would you like to be added**:
Inject AWS_REGION environment variable into pods.

**Why is this needed**:
Pods using AWS SDK languages like Go and Java need [**AWS_REGION**](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-the-region) environment variable to talk to proper STS endpoint. 

Boto based Python application needs [**AWS_DEFAULT_REGION**](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#environment-variable-configuration) env variable, per 

I noticed [this commit](https://github.com/aws/amazon-eks-pod-identity-webhook/commit/aab50cad35df4f7096d916256055b4921f81bd12) has added the **AWS_DEFAULT_REGION** env variable into pods, Could you please considering also add  **AWS_REGION** into pods?

**Comment by josselin-c** [comment]
Good call, looking into this.

**Comment by jammerful** [comment]
@micahhausler @josselin-c Has this change been rolled out, I'm not seeing any `AWS_*_REGION` variables injected into my pod's environment variable section. I'm running 1.15 on a fresh cluster.

```
    env:
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::<acct_id>:role/<role_name>
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
