### ISSUE TITLE
Injection sometimes fails on pods created from deployments

### ISSUE THREAD

**Issue by kragniz** [aws/amazon-eks-pod-identity-webhook#83]
**What happened**:

Volume and environment config was not injected into pods created from a deployment.

**What you expected to happen**:

The config to be injected, or some debug information about why the injection didn't happen.

**How to reproduce it (as minimally and precisely as possible)**:

Creating a couple of pods with a direct pod and a deployment:

```
(๑•ᴗ•)⊃━~/g/irsa-reproducer━☆ﾟ cat reproducer.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test-app
spec:
  serviceAccount: test-app
  serviceAccountName: test-app
  containers:
  - name: hello
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: test-app-token-njbrl
      readOnly: true
  volumes:
  - name: test-app-token-njbrl
    secret:
      defaultMode: 420
      secretName: test-app-token-njbrl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      serviceAccount: test-app
      serviceAccountName: test-app
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'sleep 3600']
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: test-app-token-njbrl
          readOnly: true
      volumes:
      - name: test-app-token-njbrl
        secret:
          defaultMode: 420
          secretName: test-app-token-njbrl
```

And applying together:

```
(๑•ᴗ•)⊃━~/g/irsa-reproducer━☆ﾟ kubectl apply -f reproducer.yaml
```

Results in the directly created pod receiving the injected config, but sometimes not the pod created by the deployment:

```
(๑•ᴗ•)⊃━~/g/irsa-reproducer━☆ﾟ kubectl get pods -n test-app -o jsonpath='{range .items[*]}{@.metadata.name}{" (serviceAccount: "}{@.spec.serviceAccount}{") "}{@.spec.volumes[*].name}{"\n"}{end}'
test-deploy-6794999d9-cqkwm (serviceAccount: test-app) test-app-token-njbrl
test-pod (serviceAccount: test-app) aws-iam-token test-app-token-njbrl
```

**Anything else we need to know?**:

This happens much more regularity (almost guaranteed) on an EKS cluster in one of our AWS accounts, but not in other accounts.

Feels somewhat similar to https://github.com/godaddy/kubernetes-external-secrets/issues/419

**Environment**:
- AWS Region: eu-west-1
- EKS Platform version: `eks.2`
- Kubernetes version: `1.17`
- Webhook Version:

**Comment by allamand** [comment]
@kragniz Did you see specific errors in `kubectl get events` when this appears ?
Are you working in EKS ? normally you do not need to specify the volumeMounts in EKS: [example](https://github.com/allamand/eksutils/blob/master/eksutils-deployment.yaml)

**Comment by kragniz** [comment]
@allamand volumeMounts doesn't need to be added, but I included it to be explicit about which mounts were being added.

Here's another instance (but without the explicit volumes for the service token):

 ```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test-app
spec:
  serviceAccount: test-app
  serviceAccountName: test-app
  containers:
  - name: hello
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      serviceAccount: test-app
      serviceAccountName: test-app
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'sleep 3600']
```

When watching `kubectl get events -A -w` while applying:

```
test-app    0s          Normal    Scheduled           pod/test-pod                                             Successfully assigned test-app/test-pod to ip-172-31-3-158.eu-west-1.compute.internal
test-app    0s          Normal    ScalingReplicaSet   deployment/test-deploy                                   Scaled up replica set test-deploy-fdfc554f to 1
test-app    0s          Normal    SuccessfulCreate    replicaset/test-deploy-fdfc554f                          Created pod: test-deploy-fdfc554f-sd7nb
test-app    0s          Normal    Scheduled           pod/test-deploy-fdfc554f-sd7nb                           Successfully assigned test-app/test-deploy-fdfc554f-sd7nb to ip-172-31-18-62.eu-west-1.compute.internal
test-app    0s          Normal    Pulling             pod/test-pod                                             Pulling image "busybox"
test-app    0s          Normal    Pulled              pod/test-pod                                             Successfully pulled image "busybox"
test-app    0s          Normal    Created             pod/test-pod                                             Created container hello
test-app    0s          Normal    Started             pod/test-pod                                             Started container hello
test-app    1s          Normal    Pulling             pod/test-deploy-fdfc554f-sd7nb                           Pulling image "busybox"
test-app    0s          Normal    Pulled              pod/test-deploy-fdfc554f-sd7nb                           Successfully pulled image "busybox"
test-app    0s          Normal    Created             pod/test-deploy-fdfc554f-sd7nb                           Created container hello
test-app    0s          Normal    Started             pod/test-deploy-fdfc554f-sd7nb                           Started container hello
```

In this instance, config failed to be injected into either of the pods:

```
(๑•ᴗ•)⊃━~/g/irsa-reproducer━☆ﾟ kubectl get pods -n test-app -o jsonpath='{range .items[*]}{@.metadata.name}{" (serviceAccount: "}{@.spec.serviceAccount}{") "}{@.spec.volumes[*].name}{"\n"}{end}'
test-deploy-fdfc554f-sd7nb (serviceAccount: test-app) test-app-token-njbrl
test-pod (serviceAccount: test-app) test-app-token-njbrl
```

Is there no way to obtain logs from the webhook that's deployed with EKS clusters?
