### ISSUE TITLE
Skip container annotations is not working for me. 

### ISSUE THREAD

**Issue by Nitesh-vaidyanath** [aws/amazon-eks-pod-identity-webhook#93]
**What happened**:
I have added below annotation as mentioned in document but still AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE environmental variable is getting added to the ignored contaIners.

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    eks.amazonaws.com/skip-containers: jaeger-agent,istio-proxy
```

**Environment**:
- AWS Region: us-east-1
- EKS Platform version: eks.3
- Kubernetes version : 1.17

**Comment by ddl-denis-parnovskiy** [comment]
Confirming the bug.

What I did: 
add annotation as follows
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: [REDACTED]
    eks.amazonaws.com/skip-containers: skip-this-container
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"eks.amazonaws.com/role-arn":"[REDACTED]"},"labels":{"app.kubernetes.io/name":"denis-test-account-name","aws.cdk.eks/prune-[REDACTED]":""},"name":"denis-test-account-name","namespace":"default"}}
  labels:
    app.kubernetes.io/name: denis-test-account-name
    aws.cdk.eks/prune-[REDACTED]: ""
  name: denis-test-account-name
  namespace: default
secrets:
- name: denis-test-account-name-token-2lpn6
```

Then run a job
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - command: ["bash", "-c", "ls -R /var/run/secrets"]
        image: amazon/aws-cli
        imagePullPolicy: Always
        name: skip-this-container
      dnsPolicy: ClusterFirst
      serviceAccountName: denis-test-account-name
      restartPolicy: Never
```

Result from kubectl get pod
```
spec:
  containers:
  - command:
    - bash
    - -c
    - ls -R /var/run/secrets
    env:
    - name: AWS_DEFAULT_REGION
      value: us-west-2
    - name: AWS_REGION
      value: us-west-2
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::890728157128:role/denis-test1-eks-stack-eksdenistestaccountRole27310-BNN2YDEVTZ9D
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    image: amazon/aws-cli
    imagePullPolicy: Always
    name: skip-this-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: denis-test-account-name-token-2lpn6
      readOnly: true
    - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      name: aws-iam-token
      readOnly: true
```
